---
title: "Pedotransfer functions for estimating carbon and organic matter content in Rio Grande do Sul, Brazil"
author: "Alessandro Samuel-Rosa, Douglas Adams Weiler, Sandro Giacomini"
date: "12 October 2017"
bibliography: "~/Dropbox/jabref/biblio.bib"
csl: abnt.csl
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract {-}

**Index terms**:

# Introduction

There exist several analythical methods to directly measure the content of carbon in soil samples. The standard method for measuring the total carbon content is the dry combustion method, which is based on the oxidation of both organic and inorganic forms of carbon at very high temperatures (>> 1000°C) in the presence of oxygen and copper oxide [@NelsonEtAl1996; @PansuEtAl2006]. However, wet digestion methods, which are based on the reduction of Cr~2~O~7~^2-^ by the organic compounds present in soil samples, still are commonly used [@DonagemaEtAl2011; @IUSSWorkingGroupWRB2015]. This is mainly due to three reasons: 1) implementation and maintenance costs are generally lower than for the standard method; 2) the accuracy is comparable to the estandard method -- provided that the quantity of inorganic forms of carbon is negligible; 3) used in most soil classification and fertilizer recomendation systems. [ADICIONAR ROLAS COMO REFERÊNCIA ACIMA]

Wet digestion methods have long been criticized because the ion Cr^6+^ is toxic for all forms of life [@RodellaEtAl1994; @PimentelEtAl2006]. Because of this the loss on ignition method has been proposed as a substitute for the wet digestion method used in research laboratories and in the routine analysis of the laboratories under the Official Network of Laboratories for the Analysis of Soil and Plant Tissue of the States of Rio Grande do Sul and Santa Catarina (ROLAS) [@BrunettoEtAl2006; @EscosteguyEtAl2007]. It has also been recognized the need for calibrating the several methods to the standard method, i.e. dry combustion [@RheinheimerEtAl2008, @GattoEtAl2009].

A few studies were developed in Brazil in the last decade in order to compare different methods and find proper pedotransfer functions -- more specificaly correction factors -- to the standard method. However, none of them compared the wet digestion, the loss on ignition, the routine method used in laboratories under ROLAS (wet digestion) and the standard dry combustion method at once. Besides, a few issues related to the representativeness of the datasets and to statistical assumptions appear in all studies.

The loss on ignition method was evaluated as a substitute for the wet digestion and routine method by @BrunettoEtAl2006. However, they used only *n* = 19 soil samples from the Serra Gaúcha region of the State of Rio Grande do Sul (RS). The clay content of the samples ranges between 210 and 530 g kg^-1^ and the organic matter content ranges between 2.9% and 13.3%. Besides, the data has an asymmetric distribution, with most data points concentrated bellow the value of 8% of organic matter. In similar study @EscosteguyEtAl2007 evaluated the loss on ignition method as a substitute for the routine method, using *n* = 19 soil samples from eleven soil classes of the RS (clay content ranging between 89 and 729 g kg^-1^) and *n* = 49 soil samples (sandy soils) from the Central Depression region of the RS. The organic matter content of the samples is bellow 5.5% and the data has a normal distribution.

The precision of the wet digestion method in estimating the organic matter content of soils measured by the dry combustion method was evaluated by @RheinheimerEtAl2008. They used *n* = 18 soil samples from a Ferralsol from the Planalto region of the RS and *n* = 75 soil samples from an Acrisol from the Central Depression region of the RS. The first set has a clay content ranging between 352 a 425 g kg^-1^ and the second set has a clay content ranging between 95 a 468 g kg^-1^. The organic matter content of the samples ranges between 0.3% and 7.0% and the data has an asymmetric distribution. In order to establish pedotransfer functions to estimate the organic matter content of soils from different climatic conditions under Eucaliptus plantation, @GattoEtAl2009 compared the wet digestion with the dry combustion method. They used *n* = 99 soil samples from three soil classes collected in the Centro-Leste region of the State of Minas Gerais. No information is given about the clay content and mineralogy of the soils. The organic matter content in soils is bellow 4.0% and the data has a normal distribution.

The present study takes place due to the poor representativeness and failure in attending to statistical assumptions of datasets used in previous studies and the need for more information about the loss on ignition method. The primary objective is to evaluate the use of three methods (wet digestion, loss on ignition and the routine method) to estimate the organic carbon/matter content of soils measured by the dry combustion method. Second, to evaluate the loss on ignition method as a substitute method for the routine method used in laboratories under ROLAS.

# Material and Methods

## Soil samples description and preparation

We evaluated the methods of estimating the organic carbon/matter content in *n* = 105 air-dried < 2 mm-soil samples collected at 27 sites in the State of Rio Grande do Sul (RS), Brazil. The samples cover eleven soil groups (Acrisols, Alisols, Cambisols, Ferralsols, Fluvisols, Gleysols, Leptosols, Nitisols, Planosols, Regosols, and Vertisols) derived from several parent materials (sedimentary, volcanic, and metamorphic). The clay content of the soil samples varies between 40 and 800 g kg^-1^. The mineralogical assemblage is diverse (quartz, iron oxide, and 2:1 and 1:1 phyllosilicates). Several land use types are represented: rangeland, farmland, fallow land, plantation (Eucalyptus sp.) and native forests. The climate of the sampling sites varies from humid subtropical to temperate climate, both without a defined dry season. Mean annual precipitation across RS ranges from approximately 1300 to 2000 mm. The mean annual temperature across RS is about 18°C, whichever is colder in higher sites (> 800 m a.s.l.) and warmer in lower sites (< 200 m a.s.l.). Soil samples collection procedures are described elsewhere [@CasaliEtAl2006, Barros (2007), @Britzke2010, @PotesEtAl2010, Vieira (2010), @Samuel-RosaEtAl2013a, @Samuel-RosaEtAl2013]. We grounded the soil samples in an agate mortar (< 1 mm) and stored them in microtubes (Eppendorf type) in the dark at room temperature until analysis.

## Analytical methods

### Dry combustion

Sample aliquots of 50 to 60 mg [ESTES VALORES ESTÃO CORRETOS???] in titanium capsules were used to estimate the total soil organic carbon content in an elementary CHNS analyzer (FlashEA 1112, Thermo Finnigan, Milan, Italy). We transformed the results to organic matter content using the Van Bemmelen factor (1.724). This factor considers that soil organic matter is composed of 58% of organic carbon. [NÃO FAZ SENTIDO TRANSFORMAR ESSES DADOS!!!]

### Loss on ignition

Sample aliquots of 300 to 500 mg in hand-made aluminum capsules (20 mg) (oven dried at 360°C) were placed in an oven at 105°C for 24 hours. We varied the sample aliquot used due to sample availability what had no noticeable effect on the analytical results as showed by linear correlation analysis (data not shown). Next, we placed the oven-dried samples in a desiccator containing silica gel and weighted after they had cooled down. The amount of mass lost between the first and second weightings was used to calculate the water content in the sample. Next, we placed the samples in an oven at 360ºC for 2 hours. Next, samples were placed in a desiccator containing silica gel and weighted after they had cooled down. The organic matter content in the samples was calculated from the mass lost between the second and third weightings. This method was adapted from @SchulteEtAl1996.

### Wet digestion I

Sample aliquots of 0.050 to 0.500 g were placed in glass digestion tubes (80 mL). The amount of sample used varied according to the SOM content estimated through visual interpretation of soil color. The correlation between SOM content and sample aliquot used as calculated in the input training dataset is r = -0.8436. Every digestion tube received an aliquot of 10 mL of 0.067 mol L-1 sulfocromic solution [K2Cr2O7 + H2SO4] and a small reflux funnel to avoid loss of reagent during digestion. A digestion block with capacity for 40 samples was used: 36 tubes with soil sample + 3 tubes with blank + 1 tube with sulfuric acid [H~2~SO~4~] and a thermometer for temperature measurement. Digestion at 150ºC last 30 min. Three blanks were prepared and set aside at room temperature to estimate the loss of reagent due to heat in the digestion block. After digestion the tubes were set aside at room temperature to cool down. Next, we transfered the solution to Erlenmeyer flasks (250 mL) with 60 mL of distilled water and 2 mL of concentrated orthophosphoric acid [H~3~PO~4~] and 3 drops of 1% diphenylamine. The solution was titrated using 0.1 mol L^-1^ ammonium ferrous sulfate [Fe(NH~4~)~2~(SO~4~])~2~.6H~2~O] until persistent green color. The results were transformed to organic matter content using the Van Bemmelen factor (1.724). This method was originaly adapted from @Mebius1960 and @YeomansEtAl1988. [NÃO FAZ SENTIDO TRANSFORMAR ESSES DADOS!!!]

### Wet digestion II

Adapted from @TedescoEtAl1995. Sample aliquots of 2.5 mL were placed in Erlenmeyer flasks (50mL). Every Erlenmeyer flask received an aliquot of 15 mL of 0.067 mol L^-1^ sulfocromic solution [Na~2~Cr~2~O~7~ + H~2~SO~4~]. The flasks were heated in a water bath at 75 to 80°C during 30 min and shaken for 5 min. A water aliquot of 15 mL was added to the flask and let overnight (15 to 18 hours). In the next day, we sampled an aliquot of 3.0 mL to a small cup with 3.0 mL of distilled water. The supernatant absorbance was measured at 645 nm. We weighted 2.5 mL of each soil sample to calculate the sample density and transform the results to a weight basis.

## Data analysis

# Results and Discussion

# References